# GitHub Template Repository Configuration
# This file configures the repository as a template for creating new Stock Verify instances

name: Stock Verify Template
description: A production-ready stock verification system with FastAPI backend and React Native frontend

# Files to exclude when creating a new repository from this template
exclude:
  - .github/workflows/  # Let new instances configure their own CI/CD
  - backend.pid
  - backend_port.json
  - .coverage
  - tmp/
  - .venv311/
  - node_modules/
  - frontend/.expo/
  - frontend/dist/

# Suggested initial setup steps for new instances
setup:
  - name: "Configure Environment Variables"
    description: "Run ./init-new-instance.sh to automatically generate environment files with secure JWT secrets"
  - name: "Configure Database Connections"
    description: "Update MongoDB and SQL Server connection strings in backend/.env"
  - name: "Install Dependencies"
    description: "The init script will install dependencies, or manually: Backend: pip install -r backend/requirements.txt | Frontend: cd frontend && npm install"
  - name: "Customize Your Instance"
    description: "Update frontend/app.json with your app name and branding"
  - name: "Start the Application"
    description: "Run ./start.sh or follow TEMPLATE_README.md for manual startup"
