#!/bin/bash
# init-new-instance.sh
# Initialization script for new Stock Verify instances created from template

set -e  # Exit on error

echo "=================================================="
echo "  Stock Verify - New Instance Initialization"
echo "=================================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to print colored output
print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

print_info() {
    echo -e "${YELLOW}ℹ $1${NC}"
}

# Step 1: Check prerequisites
echo "Step 1: Checking prerequisites..."
echo "-----------------------------------"

command -v python3 >/dev/null 2>&1 || { print_error "Python 3 is required but not installed."; exit 1; }
print_success "Python 3 found: $(python3 --version)"

command -v node >/dev/null 2>&1 || { print_error "Node.js is required but not installed."; exit 1; }
print_success "Node.js found: $(node --version)"

command -v npm >/dev/null 2>&1 || { print_error "npm is required but not installed."; exit 1; }
print_success "npm found: $(npm --version)"

command -v openssl >/dev/null 2>&1 || { print_error "openssl is required but not installed."; exit 1; }
print_success "openssl found"

echo ""

# Step 2: Generate JWT secrets
echo "Step 2: Generating secure JWT secrets..."
echo "-----------------------------------"

JWT_SECRET=$(openssl rand -base64 32)
JWT_REFRESH_SECRET=$(openssl rand -base64 32)

# Validate secret length (base64 of 32 bytes should be ~44 chars)
if [ ${#JWT_SECRET} -lt 32 ] || [ ${#JWT_REFRESH_SECRET} -lt 32 ]; then
    print_error "Generated secrets are too short. Please try again."
    exit 1
fi

print_success "JWT secrets generated successfully (length: ${#JWT_SECRET} chars)"
echo ""

# Step 3: Create environment files
echo "Step 3: Creating environment configuration..."
echo "-----------------------------------"

# Ensure backend directory exists
if [ ! -d backend ]; then
    print_warning "backend/ directory not found - creating minimal structure"
    mkdir -p backend
fi

# Ensure frontend directory exists
if [ ! -d frontend ]; then
    print_warning "frontend/ directory not found - creating minimal structure"
    mkdir -p frontend
fi

if [ ! -f backend/.env ]; then
    cat > backend/.env << EOF
# Stock Verify Backend Configuration
# Generated by init-new-instance.sh on $(date)

# Security - REQUIRED
JWT_SECRET=$JWT_SECRET
JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET

# Server Configuration
BACKEND_PORT=8001
BACKEND_HOST=0.0.0.0

# Database - MongoDB
MONGODB_URI=mongodb://localhost:27017/stock_verify

# Database - SQL Server (ERP - Read Only)
SQL_SERVER_HOST=localhost
SQL_SERVER_PORT=1433
SQL_SERVER_DATABASE=your_erp_database
SQL_SERVER_USER=your_username
SQL_SERVER_PASSWORD=your_password

# CORS Configuration
CORS_ALLOW_ORIGINS=http://localhost:8081,exp://localhost:8081

# Session Configuration
SESSION_EXPIRY_HOURS=24
REFRESH_TOKEN_EXPIRY_DAYS=7

# Rate Limiting
RATE_LIMIT_ENABLED=true
RATE_LIMIT_PER_MINUTE=60

# Logging
LOG_LEVEL=INFO
EOF
    print_success "Created backend/.env"
else
    print_warning "backend/.env already exists, skipping..."
fi

if [ ! -f frontend/.env ]; then
    cat > frontend/.env << EOF
# Stock Verify Frontend Configuration
# Generated by init-new-instance.sh on $(date)

# Backend API URL
EXPO_PUBLIC_BACKEND_URL=http://localhost:8001

# App Configuration
EXPO_PUBLIC_APP_NAME=Stock Verify
EXPO_PUBLIC_APP_VERSION=2.1.0
EOF
    print_success "Created frontend/.env"
else
    print_warning "frontend/.env already exists, skipping..."
fi

echo ""

# Step 4: Install backend dependencies
echo "Step 4: Installing backend dependencies..."
echo "-----------------------------------"

if [ -f backend/requirements.txt ]; then
    cd backend
    if [ ! -d venv ]; then
        python3 -m venv venv
        print_success "Created Python virtual environment"
    fi

    print_info "Activating virtual environment and installing packages..."
    # Portable activation - works with bash, zsh, etc.
    if [ -f venv/bin/activate ]; then
        . venv/bin/activate
    elif [ -f venv/Scripts/activate ]; then
        # Windows compatibility
        . venv/Scripts/activate
    else
        print_error "Could not find virtual environment activation script"
        cd ..
        exit 1
    fi

    pip install --quiet --upgrade pip
    pip install --quiet -r requirements.txt
    deactivate 2>/dev/null || true
    cd ..
    print_success "Backend dependencies installed"
else
    print_warning "backend/requirements.txt not found, skipping..."
fi

echo ""

# Step 5: Install frontend dependencies
echo "Step 5: Installing frontend dependencies..."
echo "-----------------------------------"

if [ -f frontend/package.json ]; then
    cd frontend
    print_info "This may take a few minutes..."
    npm install --loglevel=warn
    cd ..
    print_success "Frontend dependencies installed"
else
    print_warning "frontend/package.json not found, skipping..."
fi

echo ""

# Step 6: Set up git hooks
echo "Step 6: Setting up git hooks..."
echo "-----------------------------------"

if [ -f .pre-commit-config.yaml ]; then
    if command -v pre-commit >/dev/null 2>&1; then
        pre-commit install
        print_success "Git hooks installed"
    else
        print_warning "pre-commit not installed. Run: pip install pre-commit && pre-commit install"
    fi
else
    print_info "No pre-commit configuration found, skipping..."
fi

echo ""

# Step 7: Create necessary directories
echo "Step 7: Creating necessary directories..."
echo "-----------------------------------"

mkdir -p tmp
mkdir -p logs
mkdir -p backend/logs
mkdir -p frontend/logs

print_success "Directories created"
echo ""

# Step 8: Display next steps
echo "=================================================="
echo "  ✓ Initialization Complete!"
echo "=================================================="
echo ""
echo "📋 Next Steps:"
echo ""
echo "1. Configure your environment variables:"
echo "   - Edit backend/.env with your database credentials"
echo "   - Update SQL_SERVER_* values with your ERP connection details"
echo ""
echo "2. Customize your instance:"
echo "   - Update frontend/app.json (app name, slug, etc.)"
echo "   - Replace frontend/assets/icon.png and splash.png"
echo "   - Review backend/config.py for additional settings"
echo ""
echo "3. Start the application:"
echo "   - Quick start: ./start.sh"
echo "   - Or follow TEMPLATE_README.md for manual startup"
echo ""
echo "4. Verify installation:"
echo "   - Backend API: http://localhost:8001/api/docs"
echo "   - Frontend: Run 'cd frontend && npm start'"
echo "   - Health check: http://localhost:8001/health"
echo ""
echo "5. Review documentation:"
echo "   - Template setup: TEMPLATE_README.md"
echo "   - Architecture: docs/ARCHITECTURE.md"
echo "   - API reference: docs/API_REFERENCE.md"
echo ""
echo "📖 For detailed instructions, see: TEMPLATE_README.md"
echo ""
echo "🔐 Security Reminders:"
echo "   - Never commit .env files"
echo "   - Keep JWT secrets secure (already in .gitignore)"
echo "   - Review CORS settings before production deployment"
echo ""
echo "Good luck with your Stock Verify deployment! 🚀"
echo ""
