import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0F172A",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 20,
    paddingTop: Platform.OS === "ios" ? 60 : 40,
    backgroundColor: "#1E1E1E",
    borderBottomWidth: 1,
    borderBottomColor: "#2C2C2C",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#fff",
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  toggleButton: {
    padding: 8,
  },
  historyButton: {
    padding: 8,
  },
  headerCenter: {
    flex: 1,
    alignItems: "center",
  },
  headerSubtitle: {
    fontSize: 12,
    color: "#94A3B8",
    marginTop: 2,
  },
  logoutButton: {
    padding: 8,
  },
  datePickerButton: {
    backgroundColor: "#1E293B",
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: "#334155",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  datePickerButtonText: {
    color: "#fff",
    fontSize: 16,
  },
  clearDateButton: {
    position: "absolute",
    right: 12,
    top: 38,
  },
  readOnlyInfoSection: {
    backgroundColor: "#1E293B",
    borderRadius: 8,
    padding: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: "#334155",
  },
  autoIncrementBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(76, 175, 80, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(76, 175, 80, 0.35)",
    borderRadius: 8,
    padding: 12,
    margin: 16,
  },
  autoIncrementText: {
    color: "#3B82F6",
    fontSize: 14,
    flex: 1,
  },
  content: {
    flex: 1,
    padding: 16,
  },
  input: {
    backgroundColor: "#1E293B",
    borderRadius: 8,
    padding: 12,
    color: "#fff",
    fontSize: 16,
    borderWidth: 1,
    borderColor: "#334155",
    marginBottom: 16,
  },
  text: {
    color: "#fff",
    fontSize: 16,
  },
  scanButton: {
    backgroundColor: "#3B82F6",
    borderRadius: 24,
    padding: 48,
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    shadowColor: "#3B82F6",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 10,
  },
  scanButtonDisabled: {
    backgroundColor: "#2C2C2C",
    shadowOpacity: 0,
  },
  scanButtonText: {
    color: "#000",
    fontSize: 22,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  webNotice: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "rgba(255, 183, 77, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(255, 183, 77, 0.35)",
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
  },
  webNoticeText: {
    color: "#FFB74D",
    fontSize: 13,
    flex: 1,
  },
  orDivider: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 32,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: "#334155",
  },
  orText: {
    color: "#94A3B8",
    marginHorizontal: 16,
    fontSize: 16,
  },
  searchContainer: {
    marginBottom: 16,
  },
  manualEntryContainer: {
    marginTop: 8,
  },
  manualEntryTitle: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 16,
    textAlign: "center",
  },
  inputGroup: {
    marginBottom: 16,
  },
  inputLabelContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  inputLabel: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
    marginLeft: 8,
  },
  manualInput: {
    backgroundColor: "#1E293B",
    color: "#fff",
    padding: 14,
    borderRadius: 8,
    fontSize: 16,
    borderWidth: 1,
    borderColor: "#334155",
    marginBottom: 8,
  },
  inputDivider: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 12,
  },
  searchButton: {
    backgroundColor: "#3B82F6",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 12,
    borderRadius: 8,
    marginTop: 4,
  },
  searchButtonDisabled: {
    backgroundColor: "#334155",
    opacity: 0.5,
  },
  searchButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
    marginLeft: 8,
  },
  searchingContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
  },
  searchingText: {
    color: "#94A3B8",
    fontSize: 14,
    marginLeft: 8,
  },
  searchLabel: {
    fontSize: 16,
    color: "#fff",
    marginBottom: 12,
    fontWeight: "bold",
  },
  searchInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#252525",
    borderRadius: 16,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: "#334155",
    height: 60,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  searchIcon: {
    marginRight: 12,
  },
  searchInput: {
    flex: 1,
    height: "100%",
    color: "#fff",
    fontSize: 18,
    fontWeight: "500",
  },
  searchResultsContainer: {
    backgroundColor: "#1E293B",
    borderRadius: 12,
    marginTop: 8,
    maxHeight: 400,
    borderWidth: 1,
    borderColor: "#3B82F6",
  },
  searchResultsScrollView: {
    maxHeight: 350,
  },
  searchResultsTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#3B82F6",
    marginBottom: 12,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#334155",
  },
  searchResultsList: {
    padding: 8,
  },
  searchResultItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 14,
    backgroundColor: "#1E293B",
    borderRadius: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#334155",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 3,
  },
  searchResultItemLast: {
    borderBottomWidth: 0,
  },
  searchResultContent: {
    flex: 1,
  },
  searchResultLeft: {
    flex: 1,
  },
  searchResultName: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 4,
  },
  searchResultMeta: {
    flexDirection: "row",
    gap: 8,
  },
  searchResultCode: {
    fontSize: 12,
    color: "#94A3B8",
  },
  searchResultBarcode: {
    fontSize: 12,
    color: "#94A3B8",
    marginTop: 2,
  },
  searchResultStock: {
    fontSize: 13,
    color: "#3B82F6",
    marginTop: 4,
    fontWeight: "600",
  },
  searchResultRight: {
    alignItems: "flex-end",
    marginLeft: 12,
  },
  searchResultStockLabel: {
    fontSize: 11,
    color: "#94A3B8",
  },
  noResultsContainer: {
    alignItems: "center",
    paddingVertical: 32,
  },
  noResultsText: {
    fontSize: 16,
    color: "#94A3B8",
    marginTop: 12,
    marginBottom: 4,
  },
  noResultsHint: {
    fontSize: 14,
    color: "#666",
  },
  searchTips: {
    backgroundColor: "#1a2a1a",
    borderRadius: 12,
    padding: 16,
    marginTop: 16,
    borderWidth: 1,
    borderColor: "#2a4a2a",
  },
  searchTipsTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#3B82F6",
    marginBottom: 8,
  },
  searchTip: {
    fontSize: 13,
    color: "#94A3B8",
    marginBottom: 4,
    lineHeight: 18,
  },
  itemCard: {
    backgroundColor: "#1E1E1E",
    borderRadius: 24,
    padding: 24,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "rgba(0, 230, 118, 0.3)",
    shadowColor: "#3B82F6",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
  },
  itemName: {
    fontSize: 28,
    fontWeight: "800",
    color: "#fff",
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  itemCode: {
    fontSize: 14,
    color: "#94A3B8",
    marginBottom: 4,
  },
  itemBarcode: {
    fontSize: 14,
    color: "#94A3B8",
    marginBottom: 4,
  },
  locationRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 4,
    marginBottom: 4,
  },
  locationText: {
    fontSize: 14,
    color: "#3B82F6",
    marginLeft: 6,
    fontWeight: "600",
  },
  itemCategory: {
    fontSize: 13,
    color: "#94A3B8",
    marginTop: 4,
    marginBottom: 12,
  },
  uomText: {
    fontSize: 12,
    color: "#94A3B8",
    marginTop: 4,
  },
  verificationBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1a3a1a",
    padding: 8,
    borderRadius: 8,
    marginTop: 8,
    marginBottom: 12,
  },
  verificationText: {
    fontSize: 12,
    color: "#3B82F6",
    marginLeft: 6,
    fontWeight: "600",
  },
  verificationTime: {
    fontSize: 11,
    color: "#94A3B8",
    fontWeight: "400",
  },
  qtyRow: {
    flexDirection: "row",
    gap: 16,
  },
  qtyBox: {
    flex: 1,
    backgroundColor: "#1E293B",
    borderRadius: 12,
    padding: 12,
  },
  qtyLabel: {
    fontSize: 12,
    color: "#94A3B8",
    marginBottom: 4,
  },
  qtyValue: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#3B82F6",
  },
  qtyHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  refreshButton: {
    padding: 4,
    borderRadius: 4,
    backgroundColor: "#1E293B",
  },
  refreshButtonDisabled: {
    opacity: 0.5,
  },
  countingSection: {
    marginTop: 8,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 16,
  },
  countInput: {
    backgroundColor: "#252525",
    borderRadius: 16,
    padding: 20,
    color: "#fff",
    fontSize: 32,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#334155",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 2,
  },
  fieldLabel: {
    color: "#bbb",
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 8,
    marginTop: 8,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  mrpInput: {
    fontSize: 22,
    fontWeight: "700",
  },
  mrpChangeBox: {
    backgroundColor: "#1E293B",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#334155",
  },
  mrpChangeLabel: {
    color: "#94A3B8",
    fontSize: 14,
    marginBottom: 4,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  mrpChangeValue: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
  mrpChangeNotice: {
    color: "#ffb74d",
    fontSize: 12,
    textAlign: "center",
    marginTop: 8,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  mrpVariantsContainer: {
    backgroundColor: "#1f1f1f",
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: "#334155",
    marginBottom: 16,
  },
  mrpVariantsLabel: {
    color: "#94A3B8",
    fontSize: 13,
    marginBottom: 8,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  mrpVariantsChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  mrpVariantChip: {
    borderWidth: 1,
    borderColor: "#3B82F6",
    borderRadius: 16,
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: "rgba(76, 175, 80, 0.1)",
  },
  mrpVariantChipActive: {
    backgroundColor: "#3B82F6",
  },
  mrpVariantChipText: {
    color: "#3B82F6",
    fontSize: 13,
    fontWeight: "600",
  },
  mrpVariantChipTextActive: {
    color: "#1E293B",
  },
  mrpVariantChipMeta: {
    color: "#9ccc9c",
    fontSize: 11,
    marginTop: 4,
    letterSpacing: 0.2,
  },
  mrpVariantChipMetaActive: {
    color: "#0d4d1a",
  },
  mrpIncrease: {
    color: "#3B82F6",
  },
  mrpDecrease: {
    color: "#EF4444",
  },
  mrpNeutral: {
    color: "#fff",
  },
  subSectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#fff",
  },
  serialSection: {
    marginTop: 8,
    marginBottom: 16,
    backgroundColor: "#1f1f1f",
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "#334155",
    gap: 12,
  },
  serialHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  serialToggleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  serialToggleLabel: {
    color: "#bbb",
    fontSize: 13,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  serialRequirementText: {
    color: "#94A3B8",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  serialHelperText: {
    color: "#ffb74d",
    fontSize: 12,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  serialErrorText: {
    color: "#ff5252",
    fontSize: 12,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  serialInputsContainer: {
    gap: 12,
  },
  serialInputRow: {
    flexDirection: "column",
    gap: 10,
    backgroundColor: "#1E293B",
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: "#334155",
  },
  serialInputRowActive: {
    borderColor: "#3B82F6",
    backgroundColor: "#233323",
  },
  serialInputHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  serialInputActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  serialActionButton: {
    padding: 8,
    borderRadius: 18,
    backgroundColor: "rgba(76, 175, 80, 0.12)",
  },
  serialInputLabel: {
    color: "#bbb",
    fontSize: 13,
    fontWeight: "600",
    minWidth: 90,
  },
  serialTextInput: {
    flex: 1,
    backgroundColor: "#1E293B",
    color: "#fff",
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#334155",
    fontSize: 14,
  },
  removeSerialButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: "rgba(255, 82, 82, 0.1)",
  },
  serialControlsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  scanSerialButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "rgba(76, 175, 80, 0.15)",
    borderWidth: 1,
    borderColor: "#3B82F6",
  },
  scanSerialButtonText: {
    color: "#3B82F6",
    fontSize: 14,
    fontWeight: "600",
  },
  addSerialButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "rgba(76, 175, 80, 0.1)",
    borderWidth: 1,
    borderColor: "#3B82F6",
  },
  addSerialButtonText: {
    color: "#3B82F6",
    fontSize: 14,
    fontWeight: "600",
  },
  serialOverlayBadge: {
    marginLeft: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: "rgba(76, 175, 80, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(76, 175, 80, 0.35)",
  },
  serialOverlayText: {
    color: "#3B82F6",
    fontSize: 12,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  photoSection: {
    marginBottom: 16,
    backgroundColor: "#1f1f1f",
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "#334155",
    gap: 12,
  },
  photoSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  photoCountLabel: {
    color: "#94A3B8",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  photoHelper: {
    color: "#777",
    fontSize: 13,
    marginBottom: 4,
  },
  photoWebNotice: {
    color: "#FFB74D",
    fontSize: 12,
    marginBottom: 8,
  },
  photoSerialWarning: {
    color: "#ff5252",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  photoTypePills: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  photoTypePill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#3B82F6",
    backgroundColor: "rgba(76, 175, 80, 0.08)",
  },
  photoTypePillActive: {
    backgroundColor: "#3B82F6",
  },
  photoTypeIcon: {
    marginTop: 1,
  },
  photoTypeText: {
    color: "#3B82F6",
    fontSize: 13,
    fontWeight: "600",
  },
  photoTypeTextActive: {
    color: "#1E293B",
  },
  photoControls: {
    flexDirection: "row",
    alignItems: "center",
  },
  photoCaptureButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#3B82F6",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 20,
  },
  photoCaptureButtonDisabled: {
    backgroundColor: "#3a3a3a",
    opacity: 0.6,
  },
  photoCaptureButtonText: {
    color: "#1E293B",
    fontSize: 14,
    fontWeight: "600",
  },
  photoPreviewList: {
    marginTop: 8,
  },
  photoPreviewItem: {
    width: 120,
    height: 120,
    borderRadius: 12,
    overflow: "hidden",
    marginRight: 12,
    borderWidth: 1,
    borderColor: "#334155",
  },
  photoPreviewImage: {
    width: "100%",
    height: "100%",
  },
  photoPreviewMeta: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
  },
  photoPreviewLabel: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "600",
    textTransform: "capitalize",
  },
  photoRemoveButton: {
    padding: 4,
    borderRadius: 12,
    backgroundColor: "rgba(255, 82, 82, 0.85)",
  },
  photoEmptyText: {
    color: "#666",
    fontSize: 13,
  },
  photoModalContainer: {
    flex: 1,
    backgroundColor: "#000",
  },
  photoCamera: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },
  photoModalOverlay: {
    flex: 1,
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 16,
  },
  photoModalTopBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  photoModalButton: {
    backgroundColor: "rgba(26, 26, 26, 0.85)",
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.15)",
  },
  photoModalButtonText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "600",
  },
  photoShutterBar: {
    alignItems: "center",
  },
  photoShutterButton: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 4,
    borderColor: "#fff",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
  },
  photoShutterInner: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#fff",
  },
  conditionSection: {
    marginBottom: 16,
    backgroundColor: "#1f1f1f",
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "#334155",
    gap: 12,
  },
  conditionHelper: {
    color: "#94A3B8",
    fontSize: 13,
  },
  conditionChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  conditionChip: {
    borderWidth: 1,
    borderColor: "#555",
    borderRadius: 16,
    paddingVertical: 6,
    paddingHorizontal: 14,
    backgroundColor: "#1E293B",
  },
  conditionChipActive: {
    borderColor: "#3B82F6",
    backgroundColor: "#3B82F6",
  },
  conditionChipText: {
    color: "#bbb",
    fontSize: 13,
    fontWeight: "600",
  },
  conditionChipTextActive: {
    color: "#1E293B",
  },
  varianceBox: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#1E293B",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    gap: 8,
  },
  varianceLabel: {
    fontSize: 16,
    color: "#94A3B8",
  },
  varianceValue: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#3B82F6",
  },
  varianceNonZero: {
    color: "#EF4444",
  },
  remarkInput: {
    backgroundColor: "#1E293B",
    borderRadius: 12,
    padding: 16,
    color: "#fff",
    fontSize: 16,
    minHeight: 80,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#334155",
  },
  actionButtons: {
    flexDirection: "row",
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: "#2C2C2C",
    borderRadius: 16,
    padding: 18,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#334155",
  },
  cancelButtonText: {
    color: "#EF4444",
    fontSize: 16,
    fontWeight: "bold",
  },
  saveButton: {
    flex: 2,
    backgroundColor: "#3B82F6",
    borderRadius: 16,
    padding: 18,
    alignItems: "center",
    shadowColor: "#3B82F6",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  saveButtonText: {
    color: "#000",
    fontSize: 18,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  scannerContainer: {
    flex: 1,
    backgroundColor: "#000",
  },
  scannerOverlay: {
    flex: 1,
    backgroundColor: "transparent",
  },
  scannerTopBar: {
    paddingTop: 60,
    paddingHorizontal: 24,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  closeScannerButton: {
    backgroundColor: "rgba(0,0,0,0.7)",
    borderRadius: 24,
    padding: 12,
  },
  continuousModeButton: {
    backgroundColor: "rgba(0,0,0,0.7)",
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  continuousModeButtonActive: {
    backgroundColor: "rgba(76, 175, 80, 0.15)",
    borderColor: "rgba(76, 175, 80, 0.45)",
  },
  continuousModeText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  continuousModeActive: {
    color: "#3B82F6",
  },
  scanFeedbackBanner: {
    position: "absolute",
    top: 120,
    left: 24,
    right: 24,
    backgroundColor: "rgba(76, 175, 80, 0.9)",
    padding: 16,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    zIndex: 10,
  },
  scanFeedbackLoading: {
    backgroundColor: "rgba(33, 150, 243, 0.9)",
  },
  scanFeedbackText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    flex: 1,
  },
  serialOverlayRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  scannerFrame: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  scannerCorner: {
    position: "absolute",
    width: 50,
    height: 50,
    borderColor: "#3B82F6",
  },
  cornerTopLeft: {
    top: "30%",
    left: "15%",
    borderTopWidth: 4,
    borderLeftWidth: 4,
  },
  cornerTopRight: {
    top: "30%",
    right: "15%",
    borderTopWidth: 4,
    borderRightWidth: 4,
  },
  cornerBottomLeft: {
    bottom: "30%",
    left: "15%",
    borderBottomWidth: 4,
    borderLeftWidth: 4,
  },
  cornerBottomRight: {
    bottom: "30%",
    right: "15%",
    borderBottomWidth: 4,
    borderRightWidth: 4,
  },
  scannerText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
    backgroundColor: "rgba(0,0,0,0.7)",
    padding: 16,
    borderRadius: 8,
  },
  scannerInstructionContainer: {
    position: "absolute",
    bottom: 100,
    left: 24,
    right: 24,
  },
  scannerSubtext: {
    color: "#94A3B8",
    fontSize: 14,
    textAlign: "center",
    backgroundColor: "rgba(0,0,0,0.6)",
    padding: 8,
    borderRadius: 8,
    marginTop: 8,
  },
  permissionContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  permissionText: {
    color: "#fff",
    fontSize: 16,
    textAlign: "center",
    marginTop: 24,
    marginBottom: 24,
  },
  permissionButton: {
    backgroundColor: "#3B82F6",
    borderRadius: 12,
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
  permissionButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  reasonOption: {
    backgroundColor: "#1E293B",
    borderRadius: 12,
    padding: 16,
    marginBottom: 8,
    borderWidth: 2,
    borderColor: "#334155",
  },
  reasonSelected: {
    borderColor: "#3B82F6",
    backgroundColor: "#1a3a1a",
  },
  reasonText: {
    color: "#fff",
    fontSize: 16,
  },
  noteInput: {
    backgroundColor: "#1E293B",
    borderRadius: 12,
    padding: 16,
    color: "#fff",
    fontSize: 16,
    minHeight: 80,
    marginTop: 8,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#334155",
  },
  confirmButton: {
    backgroundColor: "#3B82F6",
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
    marginTop: 16,
  },
  confirmButtonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
  },
  modalHeader: {
    alignItems: "center",
    marginBottom: 20,
  },
  unknownItemInfo: {
    backgroundColor: "#1E293B",
    padding: 16,
    borderRadius: 8,
    marginBottom: 16,
  },
  modalLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#94A3B8",
    marginBottom: 8,
  },
  unknownBarcode: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#3B82F6",
    fontFamily: Platform.OS === "ios" ? "Courier" : "monospace",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.8)",
    justifyContent: "center",
    padding: 24,
  },
  modalContent: {
    backgroundColor: "#1E293B",
    borderRadius: 16,
    padding: 24,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 8,
  },
  modalSubtitle: {
    fontSize: 14,
    color: "#94A3B8",
    marginBottom: 24,
  },
  voiceButton: {
    backgroundColor: "#3B82F6",
    borderRadius: 12,
    padding: 12,
    alignItems: "center",
    marginLeft: 8,
  },
  itemInfoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 16,
  },
  itemInfoItem: {
    backgroundColor: "#1E293B",
    borderRadius: 8,
    padding: 12,
    flex: 1,
    minWidth: "45%",
  },
  itemInfoText: {
    color: "#fff",
    fontSize: 14,
  },
  quickCountContainer: {
    marginBottom: 16,
  },
  quickCountLabel: {
    color: "#94A3B8",
    fontSize: 14,
    marginBottom: 8,
  },
  quickCountButtons: {
    flexDirection: "row",
    gap: 8,
  },
  quickCountButton: {
    backgroundColor: "#252525",
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 16,
    minWidth: 64,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#334155",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  quickCountButtonText: {
    color: "#3B82F6",
    fontSize: 16,
    fontWeight: "600",
  },
  locationSection: {
    marginBottom: 16,
  },
  locationGrid: {
    gap: 12,
  },
  locationInputGroup: {
    gap: 8,
  },
  locationInput: {
    backgroundColor: "#1E293B",
    borderRadius: 8,
    padding: 12,
    color: "#fff",
    fontSize: 16,
    borderWidth: 1,
    borderColor: "#334155",
  },
  optionalFieldsSection: {
    backgroundColor: "#1E293B",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#334155",
  },
  optionalFieldsToggle: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
  },
  optionalFieldsToggleText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#3B82F6",
  },
  optionalFieldsContent: {
    marginTop: 16,
    gap: 16,
  },
  optionalFieldRow: {
    gap: 12,
  },
  optionalFieldGroup: {
    gap: 8,
  },
  optionalInput: {
    backgroundColor: "#1E293B",
    borderRadius: 8,
    padding: 12,
    color: "#fff",
    fontSize: 16,
    borderWidth: 1,
    borderColor: "#334155",
  },
  readOnlyInfoTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 12,
  },
  readOnlyInfoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  readOnlyInfoLabel: {
    color: "#94A3B8",
    fontSize: 14,
  },
  readOnlyInfoValue: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "500",
  },
  unknownItemInput: {
    height: 100,
    textAlignVertical: "top",
    paddingTop: 12,
  },
  helpText: {
    fontSize: 13,
    color: "#94A3B8",
    fontStyle: "italic",
    marginTop: 8,
    marginBottom: 16,
    textAlign: "center",
  },
  modalButtons: {
    flexDirection: "row",
    gap: 12,
    marginTop: 16,
  },
  modalButton: {
    flex: 1,
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
  },
  modalSubmitButton: {
    backgroundColor: "#3B82F6",
  },
  modalSubmitButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  modalCancelButton: {
    backgroundColor: "#3a3a3a",
  },
  modalCancelButtonText: {
    color: "#fff",
    fontSize: 16,
  },
  addQtyInfo: {
    backgroundColor: "#1E293B",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
  },
  addQtyItemName: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 4,
  },
  addQtyItemCode: {
    fontSize: 14,
    color: "#94A3B8",
    marginBottom: 12,
  },
  addQtyCurrentContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  addQtyLabel: {
    fontSize: 14,
    color: "#94A3B8",
  },
  addQtyValue: {
    fontSize: 16,
    color: "#fff",
    fontWeight: "bold",
  },
  addQtyInputContainer: {
    marginVertical: 12,
  },
  addQtyInput: {
    backgroundColor: "#1E293B",
    borderRadius: 8,
    padding: 12,
    color: "#fff",
    fontSize: 18,
    textAlign: "center",
    borderWidth: 2,
    borderColor: "#3B82F6",
    marginTop: 8,
  },
  addQtyNewTotal: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "#1a3a1a",
    borderRadius: 8,
    padding: 12,
    marginTop: 8,
  },
  addQtyTotalValue: {
    fontSize: 18,
    color: "#3B82F6",
    fontWeight: "bold",
  },
  datePickerModal: {
    backgroundColor: "#1E293B",
    borderRadius: 16,
    padding: 24,
    marginHorizontal: 24,
  },
  datePickerTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 16,
    textAlign: "center",
  },
  datePickerContainer: {
    backgroundColor: "#1E293B",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
  },
  dateInput: {
    backgroundColor: "#1E293B",
    borderRadius: 8,
    padding: 12,
    color: "#fff",
    fontSize: 16,
    borderWidth: 1,
    borderColor: "#334155",
  },
  damageSection: {
    marginTop: 16,
    padding: 16,
    backgroundColor: "#1E293B",
    borderRadius: 12,
    borderLeftWidth: 4,
    borderLeftColor: "#EF4444",
  },
  damageHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  damageToggleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  damageToggleLabel: {
    fontSize: 14,
    color: "#94A3B8",
  },
  damageInputContainer: {
    marginTop: 12,
  },
  damageInput: {
    backgroundColor: "#1E293B",
    borderRadius: 8,
    padding: 12,
    color: "#fff",
    fontSize: 16,
    borderWidth: 1,
    borderColor: "#EF4444",
    marginTop: 8,
  },
  label: {
    fontSize: 14,
    fontWeight: "600",
    color: "#94A3B8",
    marginBottom: 8,
  },
  disabledButton: {
    opacity: 0.5,
  },
  locationItem: {
    flex: 1,
  },
  locationLabel: {
    fontSize: 12,
    color: "#bbb",
    marginBottom: 4,
  },
  optionalFieldsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#334155",
    marginBottom: 16,
  },
  dateButton: {
    backgroundColor: "#1E293B",
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: "#334155",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  dateButtonText: {
    color: "#fff",
    fontSize: 16,
  },
  placeholderText: {
    color: "#64748B",
  },
  damageRow: {
    flexDirection: "row",
    gap: 16,
  },
  damageItem: {
    flex: 1,
  },
  damageLabel: {
    fontSize: 14,
    color: "#bbb",
    marginBottom: 8,
  },
  conditionOptions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  conditionOption: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: "#1E293B",
    borderWidth: 1,
    borderColor: "#334155",
  },
  conditionOptionSelected: {
    backgroundColor: "#3B82F6",
    borderColor: "#3B82F6",
  },
  conditionText: {
    color: "#94A3B8",
    fontSize: 14,
    fontWeight: "500",
  },
  conditionTextSelected: {
    color: "#fff",
    fontWeight: "600",
  },
  variancePreview: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#1E293B",
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#334155",
  },
  photoHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    paddingTop: Platform.OS === "ios" ? 0 : 16,
  },
  closeButton: {
    padding: 8,
  },
  photoTitle: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "600",
  },
  flipButton: {
    padding: 8,
  },
  cameraPlaceholder: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#1E1E1E",
  },
  camera: {
    flex: 1,
  },
  captureButton: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
  },
  captureInner: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: "#000",
  },
  reasonList: {
    maxHeight: 200,
    marginBottom: 16,
  },
  reasonOptionSelected: {
    backgroundColor: "#3B82F6",
    borderColor: "#3B82F6",
  },
  reasonTextSelected: {
    fontWeight: "600",
  },
  varianceNoteInput: {
    backgroundColor: "#252525",
    borderRadius: 8,
    padding: 12,
    color: "#fff",
    fontSize: 14,
    minHeight: 80,
    textAlignVertical: "top",
    borderWidth: 1,
    borderColor: "#334155",
  },
  button: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    borderRadius: 12,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  confirmationDetails: {
    backgroundColor: "#1E293B",
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#334155",
  },
  detailText: {
    color: "#fff",
    fontSize: 16,
    marginBottom: 8,
    lineHeight: 24,
  },
  modalButtonsColumn: {
    gap: 12,
    width: "100%",
  },
  finishButton: {
    backgroundColor: "#EF4444",
  },
  confirmationModalContent: {
    backgroundColor: "#1E293B",
    borderRadius: 16,
    padding: 24,
    width: "90%",
    maxWidth: 400,
    borderWidth: 1,
    borderColor: "#334155",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
});
