const fs = require("fs");
const path = require("path");
const os = require("os");

function getLocalIpAddress() {
  const interfaces = os.networkInterfaces();
  const allAddresses = [];

  // Collect all valid IPv4 addresses
  for (const name of Object.keys(interfaces)) {
    for (const iface of interfaces[name]) {
      if (iface.family === "IPv4" && !iface.internal) {
        allAddresses.push({ name, address: iface.address });
      }
    }
  }

  // Priority 1: en0 (standard Mac WiFi)
  const en0 = allAddresses.find(idx => idx.name === 'en0');
  if (en0) return en0.address;

  // Priority 2: 192.168.0.x (common home WiFi subnet)
  const zeroSubnet = allAddresses.find(idx => idx.address.startsWith('192.168.0.'));
  if (zeroSubnet) return zeroSubnet.address;

  // Priority 3: First available
  if (allAddresses.length > 0) return allAddresses[0].address;

  return "localhost";
}

const envPath = path.resolve(__dirname, "../.env");
const localIp = getLocalIpAddress();

// Try to read port from backend_port.json (generated by backend)
let port = process.env.EXPO_PUBLIC_BACKEND_PORT || "8001";
try {
  const backendPortPath = path.resolve(__dirname, "../../backend_port.json");
  if (fs.existsSync(backendPortPath)) {
    const portData = JSON.parse(fs.readFileSync(backendPortPath, "utf8"));
    if (portData && portData.port) {
      port = portData.port.toString();
      console.log(`Detected Dynamic Backend Port: ${port}`);
    }
  }
} catch (e) {
  console.log("Could not read backend_port.json, using default port");
}

console.log(`Detected Local IP: ${localIp}`);

try {
  let envContent = fs.readFileSync(envPath, "utf8");

  // Regex to replace EXPO_PUBLIC_BACKEND_URL
  const frontendUrlRegex = /^EXPO_PUBLIC_BACKEND_URL=.*$/m;
  const newFrontendUrlLine = `EXPO_PUBLIC_BACKEND_URL=http://${localIp}:${port}`;

  if (frontendUrlRegex.test(envContent)) {
    envContent = envContent.replace(frontendUrlRegex, newFrontendUrlLine);
    console.log(`Updated EXPO_PUBLIC_BACKEND_URL to ${newFrontendUrlLine}`);
  } else {
    envContent += `\n${newFrontendUrlLine}`;
    console.log(`Added EXPO_PUBLIC_BACKEND_URL: ${newFrontendUrlLine}`);
  }

  fs.writeFileSync(envPath, envContent);
  console.log("Successfully updated .env file");
} catch (error) {
  console.error("Error updating .env file:", error);
  process.exit(1);
}
