openapi: 3.0.3
info:
  title: Stock Verify - Auth API (PIN/Password Management)
  version: 2.0.0
  description: Enhanced authentication endpoints for PIN and password management

paths:
  /api/auth/change-pin:
    post:
      summary: Change user PIN
      description: Allows authenticated user to change their 4-digit PIN
      tags: [Authentication]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [current_pin, new_pin]
              properties:
                current_pin:
                  type: string
                  pattern: '^\d{4}$'
                  example: "1234"
                  description: Current 4-digit PIN
                new_pin:
                  type: string
                  pattern: '^\d{4}$'
                  example: "5678"
                  description: New 4-digit PIN
      responses:
        '200':
          description: PIN changed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "PIN changed successfully"
                  pin_changed_at:
                    type: string
                    format: date-time
        '400':
          description: Invalid PIN format or same as current
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Current PIN is incorrect
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/auth/change-password:
    post:
      summary: Change user password
      description: Allows authenticated user to change their password
      tags: [Authentication]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [current_password, new_password]
              properties:
                current_password:
                  type: string
                  minLength: 8
                  example: "OldPassword123!"
                new_password:
                  type: string
                  minLength: 8
                  pattern: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$'
                  example: "NewSecurePass456!"
                  description: Must contain uppercase, lowercase, and digit
      responses:
        '200':
          description: Password changed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Password changed successfully"
                  password_changed_at:
                    type: string
                    format: date-time
        '400':
          description: Invalid password format or same as current
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Current password is incorrect
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/user/preferences:
    get:
      summary: Get user preferences
      description: Retrieve current user's theme and notification preferences
      tags: [User Settings]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User preferences
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPreferences'

    put:
      summary: Update user preferences
      description: Update current user's theme and notification preferences
      tags: [User Settings]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPreferencesUpdate'
      responses:
        '200':
          description: Preferences updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPreferences'
        '400':
          description: Invalid preference values
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UserPreferences:
      type: object
      properties:
        user_id:
          type: string
        color_scheme:
          type: string
          enum: [light, dark, system]
          default: system
        primary_color:
          type: string
          pattern: '^#[0-9A-Fa-f]{6}$'
          default: "#007AFF"
        font_size:
          type: string
          enum: [small, medium, large]
          default: medium
        font_scale:
          type: number
          enum: [0.85, 1.0, 1.15]
          default: 1.0
        push_notifications:
          type: boolean
          default: true
        sound_enabled:
          type: boolean
          default: true
        vibration_enabled:
          type: boolean
          default: true
        updated_at:
          type: string
          format: date-time

    UserPreferencesUpdate:
      type: object
      properties:
        color_scheme:
          type: string
          enum: [light, dark, system]
        primary_color:
          type: string
          pattern: '^#[0-9A-Fa-f]{6}$'
        font_size:
          type: string
          enum: [small, medium, large]
        push_notifications:
          type: boolean
        sound_enabled:
          type: boolean
        vibration_enabled:
          type: boolean

    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
        error_code:
          type: string
        timestamp:
          type: string
          format: date-time
